version: 2

aliases:
  - &on_master
    context: shardlabs
    filters:
      branches:
        only:
          - master

jobs:
  build_push:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run: ./build_and_push.sh
  build_push_arm:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Build and push image
          command: ./build_and_push.sh
          environment:
            TAG_SUFFIX: -arm
            MIN_VER: 0.8.1 # this should only be changed to something lower if we want to build all the arm images for those versions as well

workflows:
  version: 2
  build_push:
    jobs:
      - build_push:
          <<: *on_master
      - build_push_arm:
          <<: *on_master
