version: 2

jobs:
  build_push:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build and push image
          command: ./build_and_push.sh
          environment:
            TAG_SUFFIX: ""
            CAIRO_VERSION: "v0.11.2"
            OZ_VERSION: 0.5.1
            CAIRO_COMPILER_TARGET_TAG: "v1.1.0"
            CAIRO_COMPILER_ASSET_NAME: "release-x86_64-unknown-linux-musl.tar.gz"
            SCARB_VERSION: 0.4.0
  build_push_arm:
    docker:
      - image: cimg/deploy:2022.08
    resource_class: macos.m1.large.gen1
    steps:
      - checkout
      - run:
          name: Build and push image
          command: ./build_and_push.sh
          environment:
            TAG_SUFFIX: -arm
            CAIRO_VERSION: "v0.11.2"
            OZ_VERSION: 0.5.1
            CAIRO_COMPILER_TARGET_TAG: "v1.1.0"
            CAIRO_COMPILER_ASSET_NAME: "release-x86_64-unknown-linux-musl.tar.gz"
            SCARB_VERSION: 0.4.0

workflows:
  version: 2
  build_push:
    jobs:
      - build_push
      - build_push_arm
